git rm ob-forth.elc
git rm ob-fortran.elc
git rm ob-gnuplot.elc
git rm ob-groovy.elc
git rm ob-haskell.elc
git rm ob-io.elc
git rm ob-java.elc
git rm ob-js.elc
git rm ob-keys.elc
git rm ob-latex.elc
git rm ob-ledger.elc
git rm ob-lilypond.elc
git rm ob-lisp.elc
git rm ob-lob.elc
git rm ob-makefile.elc
git rm ob-matlab.elc
git rm ob-maxima.elc
git rm ob-mscgen.elc
git rm ob-ocaml.elc
git rm ob-octave.elc
git rm ob-org.elc
git rm ob-pandas.el
git rm ob-pandas.elc
git rm ob-perl.elc
git rm ob-picolisp.elc
git rm ob-plantuml.elc
git rm ob-processing.el
git rm ob-processing.elc
git rm ob-python.elc
git rm ob-ref.elc
git rm ob-ruby.elc
git rm ob-sass.elc
git rm ob-scala.elc
git rm ob-scheme.elc
git rm ob-screen.elc
git rm ob-sed.el
git rm ob-sed.elc
git rm ob-sh.el
git rm ob-sh.elc
git rm ob-shell.elc
git rm ob-shen.elc
git rm ob-sql.elc
git rm ob-sqlite.elc
git rm ob-table.elc
git rm ob-tangle.elc
git rm ob.elc
git rm org-agenda.elc
git rm org-archive.elc
git rm org-attach.elc
git rm org-bbdb.elc
git rm org-bibtex.elc
git rm org-capture.elc
git rm org-clock.elc
git rm org-colview.elc
git rm org-compat.elc
git rm org-crypt.elc
git rm org-ctags.elc
git rm org-datetree.elc
git rm org-docview.elc
git rm org-element.elc
git rm org-entities.elc
git rm org-eshell.elc
git rm org-faces.elc
git rm org-feed.elc
git rm org-footnote.elc
git rm org-gnus.elc
git rm org-habit.elc
git rm org-id.elc
git rm org-indent.elc
git rm org-info.elc
git rm org-inlinetask.elc
git rm org-irc.elc
git rm org-list.elc
git rm org-loaddefs.el
git rm org-macro.elc
git rm org-macs.elc
git rm org-mhe.elc
git rm org-mobile.elc
git rm org-mouse.elc
git rm org-pcomplete.elc
git rm org-plot.elc
git rm org-protocol.elc
git rm org-rmail.elc
git rm org-src.elc
git rm org-table.el.orig
git rm org-table.elc
git rm org-timer.elc
git rm org-version.el
