#!/bin/bash

echo "Starting General Backup"

RemoteBackupDir=/mnt/backup/Groups/Software/Backup/Users/Simon/simonpc
LocalBackupDir=/mnt/HDD/linux/home/simon/Backup
SimonPCArchiveName=backup-simon-simonpc

TimeStamp=$(date --date="yesterday" +%Y-%m-%d)
YesterdayArchive=$LocalBackupDir/$SimonPCArchiveName-$TimeStamp.tgz

#Calculate up MetalJet diff
echo "Calculating MetalJet Diff"
cd /home/simon/git/MetalJet/
git diff >> ../MetalJetDiff.diff

#Back up all files
echo "Archiving up All Backed-up files"
cd /
#                    Tar-File                           MetalJet Diff                      scripts     desktop shortcuts        Incoming             IPython Notebooks             Learning           Personal            configs             bash history            Notes                 SimonEnv local repo
tar -czf         $YesterdayArchive                home/simon/git/MetalJetDiff.diff  home/simon/scripts home/simon/Desktop  home/simon/Incoming home/simon/IPythonNotebooks home/simon/Learning  home/simon/Personal home/simon/.config home/simon/.bash_history /home/simon/github/Notes /home/simon/github/SimonEnv \
# Exclude the following:
#    --exclude          

#remove the diff file (otherwise it gets concatenated...)
echo "Removing MetalJet Diff file"
rm /home/simon/git/MetalJetDiff.diff

echo "Backing up yesterday's archive on 3dfs"
rsync $YesterdayArchive $RemoteBackupDir/

#  (From http://stackoverflow.com/questions/13868821/shell-script-delete-folders-older-than-n-days)
#  Explanation:
#  
#  find: the unix command for finding files / directories / links etc.
#  /path/to/base/dir: the directory to start your search in.
#  -type d: only find directories
#  -ctime +10: only consider the ones with modification time older than 10 days
#  -exec ... \;: for each such result found, do the following command in ...
#  rm -rf {}: recursively force remove the directory; the {} part is where the find result gets substituted into from the previous part.

#Remove archives older than 14 days on my machine
echo "Removing local general archives older than 14 days"
find $LocalBackupDir/*.tgz -type f -ctime +14 -exec rm {} \;

echo "Removing local logs older than 14 days"
find $LocalBackupDir/$SimonPCArchiveName-*.log -type f -ctime +14 -exec rm {} \;

#Remove archives older than 2 days on 3dfs
echo "Removing 3dfs general archives older than 7 days"
find $RemoteBackupDir/$SimonPCArchiveName-*.tgz -type f -ctime +2 -exec rm {} \;