#!/bin/bash

echo "Starting Motion Backup"

RemoteBackupDir=/mnt/3dfs/public/Groups/Software/Backup/Users/Simon/motion
LocalBackupDir=/mnt/HDD/linux/home/simon/Backup
MotionDir=/home/simon/.motion

MotionArchiveName=backup-simon-motion
TimeStamp=$(date --date="yesterday" +%Y-%m-%d)
YesterdayArchive=$LocalBackupDir/$MotionArchiveName-$TimeStamp.tgz

#Back up yesterdays motion files
echo "Archiving yesterday's files"
cd /
#This uses find | xargs since the number of files may be larger than a normal command would accept
#                Motion Dir       create tar file            Tar-File         ###Here goes the result
find $MotionDir/Tracking/Today/* | xargs tar -czf         $YesterdayArchive                

#echo "Removing yesterday's files from Today's Dir"
echo "Removing Today's Photos"
#This uses find | xargs since the number of files may be larger than a normal command would accept
#                Motion Dir       remove all files
find $MotionDir/Tracking/Today/* | xargs rm

echo "Backing up yesterday's archive on 3dfs"
rsync $YesterdayArchive $RemoteBackupDir/

#  (From http://stackoverflow.com/questions/13868821/shell-script-delete-folders-older-than-n-days)
#  Explanation:
#  
#  find: the unix command for finding files / directories / links etc.
#  /path/to/base/dir: the directory to start your search in.
#  -type d: only find directories
#  -ctime +10: only consider the ones with modification time older than 10 days
#  -exec ... \;: for each such result found, do the following command in ...
#  rm -rf {}: recursively force remove the directory; the {} part is where the find result gets substituted into from the previous part.

#Remove archives older than 14 days on my machine
echo "Removing local motion archives older than 14 days"
find $LocalBackupDir/*.tgz -type f -ctime +14 -exec rm {} \;

echo "Removing local logs older than 14 days"
find $LocalBackupDir/$MotionArchiveName-*.log -type f -ctime +14 -exec rm {} \;

#Remove archives older than 7 days on 3dfs
echo "Removing 3dfs motion archives older than 7 days"
find $RemoteBackupDir/$MotionArchiveName-* -type f -ctime +7 -exec rm {} \;

#Start Motion (If it wasn't already on)
motion
